version: "3"
services:
  db: 
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: CleanArchitecture
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - "3306:3306"
  app:
    image: golang:1.16
    environment:
      MYAPP_DATABASE_HOST: db
    command: "go run server.go"
    volumes:
      - ./Clean-Architecture
    ports:
      - "8080:8080"
    links: 
      - db

volumes:
  db-data: